In [1]:
import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import timedelta

In [2]:
df = pd.read_csv("orders.csv")

df.head()

,order_id,customer_id,customer_name,product_name,order_date,expected_delivery_date,actual_delivery_date,status,delay_days,warehouse
0,1,1777,Odika Varkey,Action Camera,2024-07-28,2024-08-07,NaN,Pending,0,Bangalore
1,2,1508,Nidra Munshi,Smart TV,2024-01-17,2024-01-23,2024-01-24,Delivered,1,Mumbai
2,3,1896,Upadhriti Talwar,Noise Cancelling Earbuds,2024-12-17,2024-12-23,NaN,Delayed,15,Chennai
3,4,1923,Hemal Nagi,USB Hub,2024-02-28,2024-03-05,NaN,Pending,0,Kolkata
4,5,1034,Anya Master,LED Desk Lamp,2024-03-13,2024-03-17,2024-03-22,Delivered,5,Hyderabad

In [3]:
fake = Faker("en_IN")

products = df["product_name"].unique().tolist()

warehouses = df["warehouse"].unique().tolist()

print(products)

print(warehouses)

['Action Camera', 'Smart TV', 'Noise Cancelling Earbuds', 'USB Hub', 'LED Desk Lamp', 'Power Bank', 'Ergonomic Chair', 'Smartphone', 'Smart Watch', 'Network Switch', 'Standing Desk', 'Wi-Fi Router', 'Drawing Tablet', 'Laptop Stand', 'Air Purifier', 'Drone', '512GB SSD', 'Graphics Card', 'HD Webcam', 'VR Headset', 'Mechanical Pencil', 'iPad Tablet', 'Wireless Mouse', 'Thermal Printer', 'Laptop', 'Gaming Chair', 'Microphone', 'Bluetooth Headphones', '27-inch Monitor', 'Ring Light', 'Portable Speaker', 'External Hard Drive', 'Mechanical Keyboard', 'USB-C Charger', 'Smart Speaker']
['Bangalore', 'Mumbai', 'Chennai', 'Kolkata', 'Hyderabad', 'Pune', 'Delhi']

In [4]:
new_orders = []

for i in range(1, 15001):

    customer_id = random.randint(1000, 9999)

    customer_name = fake.name()

    product_name = random.choice(products)

    warehouse = random.choice(warehouses)

    # Random date between 2022 and 2024
    order_date = fake.date_between(
        start_date="-3y",
        end_date="today"
    )

    expected_delivery_date = (
        order_date +
        timedelta(days=random.randint(3, 7))
    )

    # 80% delivered, 20% delayed
    if random.random() < 0.8:

        actual_delivery_date = (
            expected_delivery_date -
            timedelta(days=random.randint(0, 1))
        )

        status = "Delivered"

        delay_days = 0

    else:

        delay_days = random.randint(1, 15)

        actual_delivery_date = (
            expected_delivery_date +
            timedelta(days=delay_days)
        )

        status = "Delayed"

    new_orders.append({

        "order_id": i,

        "customer_id": customer_id,

        "customer_name": customer_name,

        "product_name": product_name,

        "order_date": order_date,

        "expected_delivery_date":
            expected_delivery_date,

        "actual_delivery_date":
            actual_delivery_date,

        "status": status,

        "delay_days": delay_days,

        "warehouse": warehouse
    })

In [5]:
orders_large = pd.DataFrame(new_orders)

orders_large.head()

,order_id,customer_id,customer_name,product_name,order_date,expected_delivery_date,actual_delivery_date,status,delay_days,warehouse
0,1,9449,Jairaj Badal,Bluetooth Headphones,2026-02-21,2026-02-26,2026-02-25,Delivered,0,Delhi
1,2,5385,Zehaan Kulkarni,Action Camera,2025-03-17,2025-03-23,2025-03-23,Delivered,0,Hyderabad
2,3,4186,Chaitaly Bora,Mechanical Pencil,2024-11-15,2024-11-19,2024-11-18,Delivered,0,Hyderabad
3,4,6933,Aashi Goyal,Action Camera,2026-04-19,2026-04-26,2026-04-26,Delivered,0,Hyderabad
4,5,1463,Saksham Date,Microphone,2024-08-15,2024-08-19,2024-08-18,Delivered,0,Kolkata

In [6]:
orders_large.shape

(15000, 10)

In [7]:
print(

    orders_large["order_date"].min()

)

print(

    orders_large["order_date"].max()

)

2023-07-03
2026-07-02

In [8]:
orders_large.to_csv(

    "orders_15000.csv",

    index=False
)

print(

    "Saved successfully!"
)

Saved successfully!